spring:
  application:
    name: todo

  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: user
    password:
    driver-class-name: org.postgresql.Driver

  h2:
    console:
      enabled: true

logging:
  level:
    com.app.todo: info